### ISSUE TITLE
Skip mame bios/devices

### ISSUE THREAD

**Issue by 5schatten** [mmatyas/pegasus-frontend#363]
Can you have a look at this PR for ES? https://github.com/RetroPie/EmulationStation/pull/432

I guess it would be pretty handy to skip listing mame & fba bios files like ES does.

Of course you have adjust it for Pegasus but at least this list https://github.com/RetroPie/EmulationStation/pull/432/files#diff-29b8b30965f0ba91f71004d563303bec should you tell which files you should skip ;-)

**Comment by 5schatten** [comment]
yes they are included as seprarate files in the `resources` folder:

> phoenix:~/.config/emulationstation/resources # ls -l
> total 3432
> -rw-rw-r--    1 root     root           268 Oct 14 22:56 arrow.svg
> -rw-rw-r--    1 root     root           482 Oct 14 22:56 busy_0.svg
> -rw-rw-r--    1 root     root           482 Oct 14 22:56 busy_1.svg
> -rw-rw-r--    1 root     root           482 Oct 14 22:56 busy_2.svg
> -rw-rw-r--    1 root     root           483 Oct 14 22:56 busy_3.svg
> -rw-rw-r--    1 root     root          1231 Oct 14 22:56 button.png
> -rw-rw-r--    1 root     root          1168 Oct 14 22:56 button_filled.png
> -rw-rw-r--    1 root     root          1932 Oct 14 22:56 cartridge.svg
> -rw-rw-r--    1 root     root           479 Oct 14 22:56 checkbox_checked.svg
> -rw-rw-r--    1 root     root           335 Oct 14 22:56 checkbox_unchecked.svg
> -rw-rw-r--    1 root     root           286 Oct 14 22:56 fav_add.svg
> -rw-rw-r--    1 root     root           215 Oct 14 22:56 fav_remove.svg
> -rw-rw-r--    1 root     root           495 Oct 14 22:56 folder.svg
> -rw-rw-r--    1 root     root          1729 Oct 14 22:56 frame.png
> drwxrwxr-x    2 root     root          4096 Dec 25 13:35 help
> -rw-r--r--    1 root     root          1457 Oct 14 22:56 mamebioses.xml
> -rw-r--r--    1 root     root         10482 Oct 14 22:56 mamedevices.xml
> -rw-rw-r--    1 root     root       3217413 Oct 14 22:56 mamenames.xml
> -rw-rw-r--    1 root     root          1363 Oct 14 22:56 off.svg
> -rw-rw-r--    1 root     root          1736 Oct 14 22:56 on.svg
> -rw-rw-r--    1 root     root         32868 Oct 14 22:56 opensans_hebrew_condensed_light.ttf
> -rw-rw-r--    1 root     root         32364 Oct 14 22:56 opensans_hebrew_condensed_regular.ttf
> -rw-rw-r--    1 root     root           247 Oct 14 22:56 option_arrow.svg
> -rw-rw-r--    1 root     root         83384 Oct 14 22:56 scroll_gradient.png
> -rw-rw-r--    1 root     root           190 Oct 14 22:56 slider_knob.svg
> -rw-rw-r--    1 root     root         19024 Oct 14 22:56 splash.svg
> -rw-rw-r--    1 root     root           807 Oct 14 22:56 star_filled.svg
> -rw-rw-r--    1 root     root           807 Oct 14 22:56 star_unfilled.svg
> -rw-rw-r--    1 root     root          1275 Oct 14 22:56 textinput_ninepatch.png
> -rw-rw-r--    1 root     root          3084 Oct 14 22:56 textinput_ninepatch_active.png
> -rw-rw-r--    1 root     root          4870 Oct 14 22:56 window_icon_256.png
>

**Comment by 5schatten** [comment]
Any progress about that? Would be nice to get rid of the bios files from the game lists.

**Comment by mmatyas** [comment]
Not yet, though I did look into the PR. The only problem I see is that the files are not really in a valid XML format (ie. the entries are not under a single root element), but I guess I can just read them line-by-line as a workaround. Other than that this shouldn't be too difficult, if nothing comes up might be added this week or the next.

By the way, do these files on the list have some extension or I can just use the as-is?

**Comment by 5schatten** [comment]
Don't pin me down on that but they should have the "typical" compressed archive ending so `.zip` `.7z` `.rar` should be common. I have only `.zip` files in my folders.

**Comment by mmatyas** [comment]
The implementation is almost done, however I've noticed that on your directory listing above the path is `~/.config/emulationstation/resources`, while according to the ES2 sources the search path is `~/emulationstation/resources` for the files. Are you using a modified ES perhaps?

**Comment by 5schatten** [comment]
I use this as base https://github.com/RetroPie/EmulationStation and added some patches to clean up Retropie leftovers from the menu while paths are untouched. The resource files are [copied over](https://github.com/5schatten/LibreELEC.tv/blob/libreelec-9.x-rr/packages/5schatten/emulation-frontends/emulationstation/package.mk#L48) from the package build dir to the config folder and ES picks them up. 

IIRC the original project https://github.com/Aloshi/EmulationStation used `~/emulationstation` in the past while the Retropie "fork" uses `~/.config/emulationstation` so both could be valid paths but I'm pretty sure only one exists at a time.

**Comment by mmatyas** [comment]
Ok, should be fixed now in the latest release!

**Comment by 5schatten** [comment]
@mmatyas 
Well it looks like it loads the bios lists but still shows `neogeo.zip` `qsound.zip` or `pgm.zip`
```
2019-04-02T23:12:32 [i] EmulationStation: Found `/storage/.emulationstation/resources/mamebioses.xml`, 70 entries loaded
2019-04-02T23:12:32 [i] EmulationStation: Found `/storage/.emulationstation/resources/mamedevices.xml`, 403 entries loaded
```

**Comment by mmatyas** [comment]
Tested again and it's working fine for me. Could you provide an example `<system>` entry and directory layout where it fails?

**Comment by 5schatten** [comment]
Directory listing:
http://ix.io/1Fet

```
	<system>
		<name>fba</name>
		<fullname>Final Burn Alpha</fullname>
		<path>/storage/roms/fba</path>
		<extension>.iso .7z .zip</extension>
		<command>/usr/bin/retroarch.start -L /tmp/cores/fbalpha_libretro.so %ROM%</command>
		<platform>arcade</platform>
                <theme>fba</theme>
	</system>
```

**Comment by mmatyas** [comment]
Ah I see the bug now, will fix it in a sec.

**Comment by mmatyas** [comment]
Ok, should work now for real.

**Comment by 5schatten** [comment]
Tested & works like a charm now.
