### ISSUE TITLE
Favourites not saved on Windows 10

### ISSUE THREAD

**Issue by PlayingKarrde** [mmatyas/pegasus-frontend#814]
### The issue

Favourites are not read when loading Pegasus. Adding a new favourite will overwrite the favourites.txt with a new one, but is still not read when reloading.

### System info

Windows 10 Pro Build 19042.804

### Pegasus version

alpha14-123-gc186669a (2021-03-10)

### Pegasus log

[lastrun.log](https://github.com/mmatyas/pegasus-frontend/files/6135563/lastrun.log)

**Comment by HVR88** [comment]
I've been meaning to report this one myself since I mentioned in your repo.

Verified with multiple themes and data sources (xml files directly or LaunchBox integration).

I believe the issue extends to reading of all other user metadata as well:  played date, play count, etc.

**Comment by mmatyas** [comment]
Ok, this should work now in the latest version!

**Comment by PlayingKarrde** [comment]
Just tested alpha14-129-g6de8ea80 (2021-03-17) and it still occurs for me.

**Comment by mmatyas** [comment]
It may have troubles loading the favorite list created with an older version, but does it still happen if you save them with the latest, and then restart?

**Comment by PlayingKarrde** [comment]
Yep I am testing by deleting my favourites.txt and restarting with none.

**Comment by mmatyas** [comment]
Does this happen with all games? Including roms, Windows EXEs and shortcuts too? Does it work in non-portable mode?

**Comment by PlayingKarrde** [comment]
Tried in non-portable to add roms, steam, and windows games and the same result.

**Comment by mmatyas** [comment]
Got it, thanks!

**Comment by PlayingKarrde** [comment]
I should note that I'm using Launchbox as my source. I'll try with some non-LB ones.

**Comment by PlayingKarrde** [comment]
OK so adding roms through the traditional way work. But Steam as a source doesn't work (nor obviously Launchbox)

**Comment by mmatyas** [comment]
This might have got fixed in the latest version, could you check?

**Comment by PlayingKarrde** [comment]
Interestingly, Launchbox works now also but Steam does not... One step closer though! This is probably enough for me to start using latest again as I've started to use LB to manage the Steam games as well but I'll keep testing as you need ^^

**Comment by PlayingKarrde** [comment]
I'm not sure if anything changed but Steam games managed through LB are no longer saved again for some reason.

**Comment by mmatyas** [comment]
Hm, I think there wasn't even a release yet this month...? The only relevant change recently seem to be the support for LaunchBox's sort title field (#829). Rather, it'd be interesting _why_ it worked in the first place :thinking:

**Comment by PlayingKarrde** [comment]
Hmm yes that's odd. I thought maybe it was because I was testing on a different system but just tried on the one that I thought worked previously and it isn't now. I wonder if I made a mistake and was using an older build when I was testing previously.

**Comment by PlayingKarrde** [comment]
Just wondering if there was any traction on this one yet? These links also don't show up in the last played filter at all so it's making Pegasus a bit of a chore to use right now (I mainly am using it for PC games these days).

**Comment by mmatyas** [comment]
There haven't been too many updates recently due to lack of time, but don't worry the issue was not forgotten.

**Comment by polson** [comment]
@mmatyas I added a PR to fix this here: https://github.com/mmatyas/pegasus-frontend/pull/860

Let me know if you want to change anything or feel free to modify it

**Comment by PlayingKarrde** [comment]
Thanks @polson that does indeed fix the favourites. They still don't show up in recently played or save their last played status so I suspect that is a separate issue.

**Comment by crono3** [comment]
I'm new to Pegasus and I'm having this issue as well (but on Windows 11). I'm attaching my lastrun.log file in case it helps... I loaded it up, favorited Blast Corps, ran the game, exited back to Pegasus, then quit.

[lastrun.log](https://github.com/mmatyas/pegasus-frontend/files/7901528/lastrun.log)

I should note that the 'favorites.txt' file does still include Blast Corps. If I re-run Pegasus and favorite other games then Blast Corp will disappear and those new games will replace it.

I'm also having problems with it remembering my latest played, most played, etc. Everything works while in app but once I quit and reload it's all gone.

**Comment by mmatyas** [comment]
There have been some Windows related fixes in the latest version, could someone check if these helped with the issue here?

**Comment by crono3** [comment]
It fixed it for me! It is now saving my favorites and my recently played games upon exit and restart. Thank you! :)

**Comment by mmatyas** [comment]
I'll assume the issue is fixed then, but feel free to report if it still occurs.
